### ISSUE TITLE
Stage uwsgi # workers different from prod

### ISSUE THREAD

**Issue by peterbe** [mozilla/socorro-infra#236]
We're running 6 workers in each webhead. That number makes sense for the prod webheads because they're big. For our tiny stage webhead it's not right.

**Comment by peterbe** [comment]
Let's track it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1281544

**Comment by willkg** [comment]
We're tracking this in bugzilla, so I'm closing this out.
