### ISSUE TITLE
buildbox needs a larger instance type to build Socorro

### ISSUE THREAD

**Issue by rhelmer** [mozilla/socorro-infra#78]
What is this, a buildbox for ants?!

**Comment by phrawzty** [comment]
![ants?](https://sp.yimg.com/ib/th?id=JN.tof3j9RSD3Kjxfxt%2bPB%2fwg&pid=15.1&P=0)

**Comment by rhelmer** [comment]
> Seriously though, I've built Socorro on t2.micro dozens of times, so it works - it's just really slow. Any ideas what we'd like to bump it up to?

Not sure, but I definitely ran out of RAM on a build recently. I think we're cutting it very close, overhead of running a CI and possibly multiple concurrent jobs is going to push us over the edge I think.

> Also, shouldn't this be a bugzilla bug? I thought we didn't use GH issues...

We did turn them off for Socorro to avoid confusion, we could do that here as well.. GH issues are much easier to deal with and more accessible by non-mozilla folks though so I am very torn on it.

I think it's fine to use issues here as long as they get translated (and likely broken down) into bugs, but if it's just causing confusion and/or consternation let's just turn off the feature.

**Comment by phrawzty** [comment]
> Not sure, but I definitely ran out of RAM on a build recently. I think we're cutting it very close, overhead of running a CI and possibly multiple concurrent jobs is going to push us over the edge I think.

Totally fair assessment of the situation, and I 100% support using a larger instance type. As long as we're regularly rotating the buildbox instances (a good idea imho) then disk won't be an issue - should we optimise for CPU or RAM, you think?

> We did turn them off for Socorro to avoid confusion, we could do that here as well.. GH issues are much easier to deal with and more accessible by non-mozilla folks though so I am very torn on it.

Yeah I'm torn on it too.  Bugzilla has the advantage of continuing to exist as long as Mozilla is around, whereas we'll lose all of the history if/when GH gets bought or whatever.  Issues have the advantage of being more inclusive and having a better user experience.  Generally at Moz we use Bugzilla, so there's precedent, but we don't need to be married to tradition.  Either way, the important thing is that we're *consistent* about it - bouncing back and forth is the worst of both worlds.

**Comment by rhelmer** [comment]
Bugzilla lacks the critical feature of inline memes, but I think we can forge ahead without it.
