### ISSUE TITLE
Missing dependencies in Socorro buildbox

### ISSUE THREAD

**Issue by rhelmer** [mozilla/socorro-infra#79]
* postgresql9.3-devel
* fpm
* packer

**Comment by phrawzty** [comment]
The buildbox has `fpm` (via `puppet/modules/socorro/manifests/packer/buildbox.pp`) and `postgresql9.3-devel` (via `puppet/modules/socorro/manifests/packer/base.pp` which is included in `puppet/modules/socorro/manifests/packer/buildbox.pp`).

Regarding those to packages, what error condition are you experiencing that has caused you to write this issue?

Packer should be added, yes.

Also, why isn't this a bugzilla bug?

**Comment by rhelmer** [comment]
Oh you know the fpm issue was a PATH issue on my end.

> Also, why isn't this a bugzilla bug?

Thanks for filing the packer bug. I was in a rush and wanted to make a quick list of things, I'll turn the missing postgres dep into a bugzilla bug now.
