### ISSUE TITLE
buildbox IAM role needs to be able to read/write AMIs

### ISSUE THREAD

**Issue by rhelmer** [mozilla/socorro-infra#80]
Packer fails on the buildbox right now:

```
$ packer build socorro_base.json 
amazon-ebs output will be in this color.

==> amazon-ebs: Inspecting the source AMI...
==> amazon-ebs: Error querying AMI: You are not authorized to perform this operation. (UnauthorizedOperation)
Build 'amazon-ebs' errored: Error querying AMI: You are not authorized to perform this operation. (UnauthorizedOperation)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error querying AMI: You are not authorized to perform this operation. (UnauthorizedOperation)

==> Builds finished but no artifacts were created.
```

**Comment by rhelmer** [comment]
There is an example of the IAM policy needed in https://www.packer.io/docs/builders/amazon.html

It looks like we don't manage IAM policies via terraform, so I went ahead and created a ` buildbox_create_ami` role policy on the buildbox AMI role.

**Comment by phrawzty** [comment]
Ok, so, I get that we're trying to move fast, but we do already have IAM profiles.  That we're not managing via Terraform is a larger issue that should be addressed - so let's work towards a sustainable solution together.
